---
editor: visual
title: "Analise Exploratoria: loan_data"
subtitle: "Estudo de modelagem de classificação"
date-format: log
format: 
  html:
    grid: 
      body-width: 950px
      margin-width: 200px
    theme: sandstone
    higlight: github
execute:
  message: false
  warning: false
code-fold: true
fig-dpi: 300
fig-width: 11
fig-height: 5
fig-align: center
toc: true
df-print: paged
editor_options: 
  chunk_output_type: inline
toc-expand: true
toc-title: "Conteúdo"
number-sections: true
fontsize: 12pt
---

```{r}
# Análise exploratória de dados: 

# Conjunto de dados: datasets/loan_data.csv
## https://www.kaggle.com/datasets/saramah/loan-data/data

# Pacotes e conjunto de dados ---------------------------------------------

library(tidyverse)
library(enoqueR)
library(gt)

dados = read_csv("datasets/loan_data.csv")
```

## Visão geral

```{r}
bind_rows(
  enoqueR::overall_info(dados),
  enoqueR::overall_tipos(dados)
  ) %>% 
  gt() %>% 
  opt_interactive()
```

```{r}
dados %>% 
  head() %>%
  gt() %>% 
  fmt_number(where(is.numeric)) %>%
  opt_interactive()
```

```{r}
variaveis_pt <- c(
  "politica_credito" = "credit.policy",
  "proposito_emp" = "purpose",
  "taxa_juros" = "int.rate",
  "parcela_mensal" = "installment",
  "log_renda_anual" = "log.annual.inc",
  "indice_divida_renda" = "dti",
  "pontuacao_fico" = "fico",
  "dias_com_credito" = "days.with.cr.line",
  "saldo_rotativo" = "revol.bal",
  "taxa_utilizacao_rotativa" = "revol.util",
  "consultas_ultimos_6_meses" = "inq.last.6mths",
  "atrasos_ultimos_2_anos" = "delinq.2yrs",
  "registros_publicos_negativos" = "pub.rec"
)
```

```{r}
dados <- dados %>% 
  rename(all_of(variaveis_pt)) %>% 
  mutate(proposito_emp = case_when(
    proposito_emp == "credit_card" ~ "Cartão de credito",
    proposito_emp == "debt_consolidation" ~ "Consolidação de divida",
    proposito_emp == "educational" ~ "Educacional",
    proposito_emp == "major_purchase" ~ "Compra grande",
    proposito_emp == "small_business" ~ "Pequeno Negócio",
    proposito_emp == "all_other" ~ "Outro",
    .default = proposito_emp
    ),
    politica_credito = fct(if_else(politica_credito == 1, "Sim", "Não"), levels = c("Não", "Sim"))
  )
```

## Análise descritiva

```{r}
dados %>% 
  enoqueR::tbl_resumo()
```

```{r}
dados %>% 
    enoqueR::variaveis() %>% 
    gt() %>% 
    fmt_number() %>% 
    tab_style(
      style = "vertical-align:middle; font-weight: bold",
      locations = cells_column_labels()
    )
```

```{r}
dados %>% 
    enoqueR::eda_tabela_dataset_resumo_num()
```

```{r}
dados %>% 
  enoqueR::eda_visual_dataset_hist()
```

```{r}
#| fig-heig: 15
dados %>% 
  enoqueR::eda_visual_dataset_resposta(resposta = "politica_credito")
```

## Próximos passos

-   Análisar associação/correlação entre a covariaveis
